org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
mod_id=loot_table_wand
mod_name=Loot Table Wand
mod_license=MIT
mod_version=1.20.1-forge-1.0.0
mod_group_id=net.mesomods
mod_authors=Mesophil
mod_description=Useful tool for in-game loot table management
source_url=https://github.com/Quatryl23/Loot-Table-Wand
issue_url=https://github.com/Quatryl23/Loot-Table-Wand/issues
