org.gradle.jvmargs=-Xmx3G
mod_version=1.0.0
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
pack_format=15
fabric_version=0.92.9+1.20.1
loader_version=0.19.3
modloader=fabric
maven_group=net.mesomods
archives_base_name=lootwand
mod_id=loot_table_wand
mod_name=Loot Table Wand
pack_description=Loot Table Wand resources
mod_license=MIT
mod_authors=Mesophil
mod_description=Useful tool for in-game loot table management
source_url=https://github.com/Quatryl23/Loot-Table-Wand
issue_url=https://github.com/Quatryl23/Loot-Table-Wand/issues
