org.gradle.jvmargs=-Xmx3G
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
fabric_version=0.92.9+1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.19.3
maven_group=net.mesomods
archives_base_name=lootwand
mod_id=loot_table_wand
mod_name=Loot Table Wand
mod_license=MIT
mod_version=1.20.1-fabric-1.0.0
mod_authors=Mesophil
mod_description=Useful tool for in-game loot table management
source_url=https://github.com/Quatryl23/Loot-Table-Wand
issue_url=https://github.com/Quatryl23/Loot-Table-Wand/issues
